package main

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"go/format"
	"io"
	"os"
	"slices"
	"strings"
)

type versionSpec struct {
	ident string
	label string
	path  string
}

var versionSpecs = []versionSpec{
	{ident: "Version200", label: "2.0.0", path: "reference/xsd/ST-Bridge_v200.xsd"},
	{ident: "Version201", label: "2.0.1", path: "reference/xsd/ST-Bridge_v201.xsd"},
	{ident: "Version202", label: "2.0.2", path: "reference/xsd/ST-Bridge_v202.xsd"},
	{ident: "Version210", label: "2.1.0", path: "reference/xsd/ST-Bridge_v210.xsd"},
}

type kindCollector struct {
	all            map[string]struct{}
	byVersion      map[string]map[string]struct{}
	versionsByName map[string]map[string]struct{}
}

func main() {
	elements := newKindCollector()
	attributes := newKindCollector()
	simpleTypes := newKindCollector()

	for _, spec := range versionSpecs {
		if err := collectFromFile(spec, elements, attributes, simpleTypes); err != nil {
			fail(err)
		}
	}

	formatted, err := format.Source(renderFile(elements, attributes, simpleTypes))
	if err != nil {
		fail(fmt.Errorf("format generated file: %w", err))
	}

	if err := os.WriteFile("names_gen.go", formatted, 0o644); err != nil {
		fail(fmt.Errorf("write names_gen.go: %w", err))
	}
}

func collectFromFile(spec versionSpec, elements, attributes, simpleTypes *kindCollector) error {
	data, err := os.ReadFile(spec.path)
	if err != nil {
		return fmt.Errorf("read %s: %w", spec.path, err)
	}

	decoder := xml.NewDecoder(bytes.NewReader(data))
	for {
		token, err := decoder.Token()
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return fmt.Errorf("decode %s: %w", spec.path, err)
		}

		start, ok := token.(xml.StartElement)
		if !ok {
			continue
		}

		switch start.Name.Local {
		case "element":
			elements.add(spec.ident, attrValue(start.Attr, "name"))
			elements.add(spec.ident, attrValue(start.Attr, "ref"))
		case "attribute":
			attributes.add(spec.ident, attrValue(start.Attr, "name"))
			attributes.add(spec.ident, attrValue(start.Attr, "ref"))
		case "simpleType":
			simpleTypes.add(spec.ident, attrValue(start.Attr, "name"))
		}
	}
}

func renderFile(elements, attributes, simpleTypes *kindCollector) []byte {
	var b bytes.Buffer

	b.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	b.WriteString("package stbridge\n\n")

	writeConstBlock(&b, "Element", "XML element", "ElementName", elements)
	writeConstBlock(&b, "Attr", "XML attribute", "AttributeName", attributes)
	writeConstBlock(&b, "SimpleType", "XSD simple type", "SimpleTypeName", simpleTypes)

	writeKnownNamesVar(&b, "knownElementNames", "ElementName", "Element", elements.names())
	writeKnownNamesVar(&b, "knownAttributeNames", "AttributeName", "Attr", attributes.names())
	writeKnownNamesVar(&b, "knownSimpleTypeNames", "SimpleTypeName", "SimpleType", simpleTypes.names())

	writeVersionedVar(&b, "knownElementNamesByVersion", "ElementName", "Element", elements.namesByVersion())
	writeVersionedVar(&b, "knownAttributeNamesByVersion", "AttributeName", "Attr", attributes.namesByVersion())
	writeVersionedVar(&b, "knownSimpleTypeNamesByVersion", "SimpleTypeName", "SimpleType", simpleTypes.namesByVersion())

	b.WriteString(`// KnownElementNames returns the published schema-backed element names.
func KnownElementNames() []ElementName {
	return append([]ElementName(nil), knownElementNames...)
}

// KnownElementNamesFor returns the published element names for version.
func KnownElementNamesFor(version Version) []ElementName {
	names := knownElementNamesByVersion[version]
	return append([]ElementName(nil), names...)
}

// KnownAttributeNames returns the published schema-backed attribute names.
func KnownAttributeNames() []AttributeName {
	return append([]AttributeName(nil), knownAttributeNames...)
}

// KnownAttributeNamesFor returns the published attribute names for version.
func KnownAttributeNamesFor(version Version) []AttributeName {
	names := knownAttributeNamesByVersion[version]
	return append([]AttributeName(nil), names...)
}

// KnownSimpleTypeNames returns the published schema-backed simple-type names.
func KnownSimpleTypeNames() []SimpleTypeName {
	return append([]SimpleTypeName(nil), knownSimpleTypeNames...)
}

// KnownSimpleTypeNamesFor returns the published simple-type names for version.
func KnownSimpleTypeNamesFor(version Version) []SimpleTypeName {
	names := knownSimpleTypeNamesByVersion[version]
	return append([]SimpleTypeName(nil), names...)
}
`)

	return b.Bytes()
}

func writeConstBlock(b *bytes.Buffer, prefix string, subject string, typeName string, collector *kindCollector) {
	fmt.Fprintf(b, "const (\n")
	for _, raw := range collector.names() {
		versions := collector.versionLabels(raw)
		fmt.Fprintf(
			b,
			"\t// %s is the raw %s name %q. %s\n",
			identifier(prefix, raw),
			subject,
			raw,
			versionSentence(versions),
		)
		fmt.Fprintf(b, "\t%s %s = %q\n", identifier(prefix, raw), typeName, raw)
	}
	fmt.Fprintf(b, ")\n\n")
}

func writeKnownNamesVar(b *bytes.Buffer, varName string, typeName string, prefix string, raws []string) {
	fmt.Fprintf(b, "var %s = []%s{\n", varName, typeName)
	for _, raw := range raws {
		fmt.Fprintf(b, "\t%s,\n", identifier(prefix, raw))
	}
	fmt.Fprintf(b, "}\n\n")
}

func writeVersionedVar(b *bytes.Buffer, varName string, typeName string, prefix string, byVersion map[string][]string) {
	fmt.Fprintf(b, "var %s = map[Version][]%s{\n", varName, typeName)
	for _, spec := range versionSpecs {
		fmt.Fprintf(b, "\t%s: {\n", spec.ident)
		for _, raw := range byVersion[spec.ident] {
			fmt.Fprintf(b, "\t\t%s,\n", identifier(prefix, raw))
		}
		fmt.Fprintf(b, "\t},\n")
	}
	fmt.Fprintf(b, "}\n\n")
}

func newKindCollector() *kindCollector {
	return &kindCollector{
		all:            map[string]struct{}{},
		byVersion:      map[string]map[string]struct{}{},
		versionsByName: map[string]map[string]struct{}{},
	}
}

func (c *kindCollector) add(version string, raw string) {
	raw = localName(raw)
	if raw == "" {
		return
	}

	c.all[raw] = struct{}{}
	if _, ok := c.byVersion[version]; !ok {
		c.byVersion[version] = map[string]struct{}{}
	}
	c.byVersion[version][raw] = struct{}{}

	if _, ok := c.versionsByName[raw]; !ok {
		c.versionsByName[raw] = map[string]struct{}{}
	}
	c.versionsByName[raw][version] = struct{}{}
}

func (c *kindCollector) names() []string {
	return sortedKeys(c.all)
}

func (c *kindCollector) namesByVersion() map[string][]string {
	out := make(map[string][]string, len(c.byVersion))
	for _, spec := range versionSpecs {
		out[spec.ident] = sortedKeys(c.byVersion[spec.ident])
	}
	return out
}

func (c *kindCollector) versionLabels(raw string) []string {
	labels := make([]string, 0, len(c.versionsByName[raw]))
	for _, spec := range versionSpecs {
		if _, ok := c.versionsByName[raw][spec.ident]; ok {
			labels = append(labels, spec.label)
		}
	}
	return labels
}

func sortedKeys[K ~string, V any](m map[K]V) []string {
	if len(m) == 0 {
		return nil
	}

	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, string(key))
	}
	slices.Sort(keys)
	return keys
}

func identifier(prefix string, raw string) string {
	raw = localName(raw)
	var b strings.Builder
	b.WriteString(prefix)
	b.WriteByte('_')
	if raw != "" && raw[0] >= '0' && raw[0] <= '9' {
		b.WriteByte('_')
	}
	for _, r := range raw {
		if r == '_' || r >= '0' && r <= '9' || r >= 'A' && r <= 'Z' || r >= 'a' && r <= 'z' {
			b.WriteRune(r)
			continue
		}
		b.WriteByte('_')
	}
	return b.String()
}

func attrValue(attrs []xml.Attr, local string) string {
	for _, attr := range attrs {
		if attr.Name.Local == local {
			return attr.Value
		}
	}
	return ""
}

func localName(raw string) string {
	raw = strings.TrimSpace(raw)
	if idx := strings.IndexByte(raw, ':'); idx >= 0 {
		return raw[idx+1:]
	}
	return raw
}

func versionSentence(labels []string) string {
	if len(labels) == 0 {
		return ""
	}
	if len(labels) == len(versionSpecs) {
		return "Present in all schema-backed versions."
	}
	if len(labels) == 1 {
		return fmt.Sprintf("Present in %s.", labels[0])
	}
	if len(labels) == 2 {
		return fmt.Sprintf("Present in %s and %s.", labels[0], labels[1])
	}

	var b strings.Builder
	b.WriteString("Present in ")
	for i, label := range labels {
		switch {
		case i == len(labels)-1:
			b.WriteString("and ")
			b.WriteString(label)
		case i == 0:
			b.WriteString(label)
			b.WriteString(", ")
		default:
			b.WriteString(label)
			b.WriteString(", ")
		}
	}
	b.WriteByte('.')
	return b.String()
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
